force-app/main/default/objects/ColumnsChangeHistory__b/ColumnsChangeHistory__b.object-meta.xml
<CustomObject>
    <label>項目変更履歴</label>
</CustomObject>

force-app/main/default/objects/ColumnsChangeHistory__b/fields/ColumnName__c.field-meta.xml
<CustomField>
    <fullName>ColumnName__c</fullName>
    <label>項目名</label>
    <length>60</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ColumnsChangeHistory__b/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ColumnsChangeHistory__b/fields/UpdatedDateTime__c.field-meta.xml
<CustomField>
    <fullName>UpdatedDateTime__c</fullName>
    <label>更新日時</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ColumnsChangeHistoryInsertActionTest.cls
@isTest 
private class ColumnsChangeHistoryInsertActionTest {
    @isTest 
    static void test() {
        List<List<ColumnsChangeHistory__b>> inputs = new List<List<ColumnsChangeHistory__b>>();
        List<ColumnsChangeHistory__b> input = new List<ColumnsChangeHistory__b>();
        input.add(new ColumnsChangeHistory__b(
            RecordId__c='test'
            , ColumnName__c = 'test'
            , UpdatedDateTime__c = Datetime.now()
        ));
        inputs.add(input);
        Test.startTest();
        ColumnsChangeHistoryInsertAction.execute(inputs);
        Test.stopTest();
    }
}